project:
  type: website
  output-dir: docs

lang: ko

website:
  title: "Data Science"
  sidebar: 
    style: floating
    contents: 
      - index.qmd
      # - text: "---"    
      # - section: "데이터사이언스 강의"
      #   contents:   
      #     - lectures.qmd
      - text: "---"    
      - section: "R과 데이터사이언스"
        contents:   
          - exec_01.qmd
          - exec_02.qmd
          - exec_03.qmd
          - exec_04.qmd
          - exec_05.qmd
          - exec_06.qmd
          - exec_07.qmd
          - exec_08.qmd
          - exec_09.qmd
          - exec_10.qmd
      - text: "---"    
      - section: "R 프레젠테이션: 2025/2"
        contents: 
          - R_lec_01_2025.qmd
          - R_lec_02_2025.qmd
          - R_lec_03_2025.qmd
          - R_lec_04_2025.qmd
          - R_lec_05_2025.qmd
          - R_lec_06_2025.qmd
      - text: "---"    
      - section: "R 프레젠테이션: 2024/1"
        contents: 
          - R_lec_01.qmd
          - R_lec_02.qmd
          - R_lec_03.qmd
          - R_lec_04.qmd
          - R_lec_05.qmd
          - R_lec_06.qmd
          - R_lec_07.qmd
          - R_lec_08.qmd
          - R_lec_09.qmd
          - R_lec_10.qmd
      - text: "---"    
      - section: "R 실습: 2025/2"
        contents: 
          - lab_01_2025.qmd
          - lab_02_2025.qmd
          - lab_03_2025.qmd
          - lab_04_2025.qmd
          - lab_05_2025.qmd
          - lab_06_2025.qmd
      - text: "---"    
      - section: "R 실습: 2024/1"
        contents: 
          - lab_01.qmd
          - lab_02.qmd
          - lab_03.qmd
          - lab_04.qmd
          - lab_05.qmd
          - lab_06.qmd
          - lab_07.qmd
          - lab_08.qmd
          - lab_09.qmd
          - lab_10.qmd

  bread-crumbs: false
  back-to-top-navigation: true
  page-navigation: true
  page-footer: 
    left: "Copyright 2024, Sang-Il Lee"
    right: 
      - icon: house
        href: https://sangillee.snu.ac.kr/
      - icon: envelope
        href: mailto:si_lee@snu.ac.kr
      - icon: github
        href: https://github.com/sangillee66
    border: true
  repo-url: https://github.com/sangillee66/data_science
  repo-actions: [issue]

format:
  html:
    theme: 
      light: [flatly, custom_basic_pretendard.scss]
      dark: [darkly, custom_basic_pretendard.scss]
    css: styles.css
    toc: true
#    embed-resources: true

execute:
  freeze: auto

# lightbox: true

editor: visual