---
title: "웹사이트 소개"
date-modified: last-modified
number-sections: false
lightbox: true
bibliography: references.bib
---

## 웹사이트의 목적

-   이 웹사이트는 데이터사이언스( Data Science)를 위한 개인 공부방으로 디자인되었다 .

-   하지만 서울대학교에서 내가 개설한 데이터 사인언스 관련 교과목의 보충 웹사이트로 활용될 수도 있다.

    -   2024/1 M3450.001400 [**AI 융합교육을 위한 인문사회 컨텐츠 설계**](https://sangillee.snu.ac.kr/classes/2024_1_AI_Edu.html) (Designing Human and Social Education Contents for AI Convergence Education)

## 웹사이트의 구조

-   데이터 사이언스 관련 내용을 모두 10개의 하위 섹션으로 나누었다.

-   각 하위 섹션은 세 개의 컨텐츠를 갖는다.

    -   내용 강의

    -   실습 강의

    -   실습

## 참고문헌

-   Wickham, Hadley, Mine Çetinkaya-Rundel, and Garrett Grolemund, 2023, [*R for Data Science: Import, Tidy, Transform, Visualize, and Model Data*](https://r4ds.hadley.nz/)*,* 2nd edition, Boston: O’Reilly. 

    -   이 사이트의 내용은 위의 책에 많은 토대를 두고 있다.

-   Wickham, Hadley, and Garrett Grolemund. 2016. [*R for Data Science: Import, Tidy, Transform, Visualize, and Model Data*](https://r4ds.had.co.nz/index.html). 1st edition. Sebastopol, CA: O’Reilly. (김설기ㆍ최혜민 옮김, 2019, [R을 활용한 데이터 과학: 데이터 불러오기, 정리하기, 변형하기, 시각화하기, 모델링하기](https://www.yes24.com/Product/Goods/67856488), 1판, 서울: 인사이트.)

-   Bonnell, Jerry, and Mitsunori Ogihara. 2023. [*Exploring Data Science with R and the Tidyverse*](https://ds4world.cs.miami.edu/). 1st edition. Chapman; Hall/CRC.

-   Irizarry, Rafael A. 2024. [*Introduction to Data Science: Data Wrangling and Visualization with R*](https://rafalab.dfci.harvard.edu/dsbook-part-1/). 2nd edition, Boca Raton: CRC Press.

-   Irizarry, Rafael A. 2024. [*Introduction to Data Science: Statistics and Prediction Algorithms Through Case Studies*](https://rafalab.dfci.harvard.edu/dsbook-part-2/). Boca Raton: CRC Press.

-   Irizarry, Rafael A. 2020. [*Introduction to Data Science: Data Analysis and Prediction Algorithms with R*](https://rafalab.dfci.harvard.edu/dsbook/). Boca Raton: CRC Press, Taylor & Francis Group.

-   Grolemund, Garrett. 2014. [*Hands-On Programming with R: Write Your Own Functions and Simulations*](https://rstudio-education.github.io/hopr/index.html). O’Reilly Media, Inc..

-   Stauffer, R., Chimiak-Opoka, Joanna, Rodríguez-R, Luis Miguel, Simon, Thorsten, Zeileis, Achim, 2024, [*Introduction to Programming with R*](https://discdown.org/rprogramming/index.html), 웹북

-   Douglas, Alex, Roos, Deon, Mancini, Francesca, Couto Ana, Lusseau, David, 2024, [*An Introduction to R*](https://intro2r.com/), 웹북

-   Batra, Neale, ed., 2024, [*The Epidemiologist R Handbook*](https://epirhandbook.com/en/index.html), 웹북

-   Doser, Jeffrey W., Finley, Andrew O., Melfi, Vince, 2022, [*R Programming for Data Sciences*](https://www.jeffdoser.com/files/for875/_book/), 웹북

-   Bonnin, Sarah, 2020, [*Introduction to R 2021*](https://biocorecrg.github.io/CRG_RIntroduction/), 웹북

-   Grolemund, Garrett, 2020, [*The Tidyverse Cookbook*](https://rstudio-education.github.io/tidyverse-cookbook/), 웹북

-   Ansell, Brendan R. E. , [*Introduction to R - tidyverse*](https://bookdown.org/ansellbr/WEHI_tidyR_course_book/), 웹북

-   Sarafian, Ron, [*Introduction to Data Science*](https://bookdown.org/ronsarafian/IntrotoDS/), 웹북

-   [*Introduction to R*](https://r-unimelb.gitbook.io/rbook), 웹북

-   [*Data Analysis and Visualization in R for Ecologists*](https://datacarpentry.org/R-ecology-lesson/index.html), 웹북

-   [*R for Epidemiology*](https://www.r4epi.com/), 웹북

-   RStudio IDE User Guide (<https://docs.posit.co/ide/user/>)

-   한국알사용자회, [데이터 과학을 지탱하는 기본기](https://r2bit.com/book_analytics/index.html), 웹북

-   한국알사용자회, [데이터 시각화](https://r2bit.com/book_viz/), 웹북

-   한국알사용자회ㆍ이광춘, 2024, [챗GPT쿼토: 인공지능 시대 과학기술 저작 도구](https://r2bit.com/gpt-quarto/), 웹북

-   김기환, 2023, [R 프로그래밍(개정판)](https://kilhwan.github.io/rprogramming/), 웹북

-   백영민. 2023. [R 기반 데이터 과학: 타이디버스(tidyverse) 접근](https://www.yes24.com/Product/Goods/123807713). 서울: 한나래아카데미.

-   차영준ㆍ박진표, 2022, [데이터과학 입문을 위한 R과 타이디버스](https://www.yes24.com/Product/Goods/111420341), 파주: 자유아카데미.

-   곽기영, 2022, [R 기초와 활용](https://www.yes24.com/Product/Goods/108044525), 서울: 청람.

-   강전희ㆍ엄동란, 2018, [처음 시작하는 R 데이터 분석](https://www.yes24.com/Product/Goods/64497252), 서울: 한빛미디어.

-   김영우, 2017, [쉽게 배우는 R 데이터 분석](https://www.yes24.com/Product/Goods/43868089), 서울: 이지스퍼블리싱.
